dist: xenial
before_install:
  - sudo apt-get update
  - sudo apt-get install --yes build-essential
  - sudo apt-get install --yes git
  - sudo apt-get install libcgal-dev, libcgal-qt5-dev
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda env create -q -f environment.yml
  - source activate tyssue
  - conda install pytest pytest-cov
  - pip install coveralls

install:
  - python setup.py install

script:
  - make coverage

after_success:
  - coveralls
