name: tyssue
channels:
- conda-forge

dependencies:
- boost-cpp
- mpfr
- python>=3.6
- numpy
- scipy
- matplotlib
- pandas
- pytables
- jupyter
- notebook
- quantities
- ipywidgets
- pythreejs
- ipyvolume
- vispy
- meshio
